version = 1

test_patterns = [
  "**/*_test.go"
]

exclude_patterns = [
  "example/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/madari/go-socket.io"
